#!/bin/bash

echo "Changing theme to $1..."

# call feh to set the background. Automatically check for jpg, if not found, suppress error by printing to null and check for png. Then call the picker function on the selected image
feh -q --bg-fill ~/Pictures/"$1".jpg 2>/dev/null && picker $HOME/Pictures/"$1".jpg || (feh -q --bg-fill $HOME/Pictures/"$1".png && picker $HOME/Pictures/"$1".png)
