#!/bin/bash

#colourshex=$(convert "$1" -format %c -colorspace LAB -colors 6 histogram:info:- | sed -e 's/.*) \(.*\)s.*/\1/');

thief=$(python $HOME/repos/dotfiles/thief.py "$1" 2>&1)
hexes=($thief)
sed -i "s/#define COLOR.*/#define COLOR mix(${hexes[4]}, ${hexes[1]}, clamp(d\/80, 0, 1))/g" /home/rroche/.config/glava/radial.glsl
sed -i "s/under =.*/under = ${hexes[5]}/g" $HOME/.config/polybar/colors.ini
glavaRunning=$(pgrep glava)
if [ $glavaRunning ] 
then
	echo "Relaunching glava..."
	kill -9 $glavaRunning
	#pkill glava 2>/dev/null; 
	exec glava &
fi
echo "Relaunching polybar..."
pkill polybar
$HOME/.config/polybar/launch.sh 2>/dev/null


# coloursrgb=$(convert "$1" -format %c -colorspace LAB -colors 6 histogram:info:- | sort -n -r | cut -d "s" -f 2 | tr -d "srgb" | tr -d "(" | tr -d ")");
# echo $coloursrgb | python3 /home/rroche/repos/dotfiles/palette.py;