#!/bin/bash

# call the colourthief routine in thief.py. This will return a list of hexes that represent the image's dominant colours
thief=$(python $HOME/repos/dotfiles/thief.py "$1" 2>&1)
hexes=($thief)

# NCMPCPP colour definitions
ncmpcpp_main=color3
ncmpcpp_headings=color11
ncmpcpp_elapsed=color21

# replace colours in glava config and polybar config with colours from the hex array
sed -i "s/#define COLOR.*/#define COLOR mix(${hexes[4]}, ${hexes[1]}, clamp(d\/80, 0, 1))/g" $HOME/.config/glava/radial.glsl
sed -i "s/under =.*/under = ${hexes[5]}/g" $HOME/.config/polybar/colors.ini
sed -i "s/$ncmpcpp_main =.*/$ncmpcpp_main = ${hexes[5]}/g" $HOME/.config/termite/config
sed -i "s/$ncmpcpp_headings =.*/$ncmpcpp_headings = ${hexes[2]}/g" $HOME/.config/termite/config


echo "Reloading termite..."
# reloads config in ALL active termite windows
killall -USR1 termite
echo "Done!"

# if glava is already running, relaunch it to refresh settings
glavaRunning=$(pgrep glava)
if [ $glavaRunning ] 
then
	echo "Relaunching glava..."
	kill -9 $glavaRunning
	#pkill glava 2>/dev/null; 
	exec glava &
	echo "Done!"
fi
# relaunch polybar to see changes
echo "Relaunching polybar..."
pkill polybar
$HOME/.config/polybar/launch.sh 2>/dev/null
echo "Done!"

# coloursrgb=$(convert "$1" -format %c -colorspace LAB -colors 6 histogram:info:- | sort -n -r | cut -d "s" -f 2 | tr -d "srgb" | tr -d "(" | tr -d ")");
# echo $coloursrgb | python3 /home/rroche/repos/dotfiles/palette.py;